### PR TITLE
Update CFloat32CustomPython.h

### PR DESCRIPTION
**Pull request by jmp1985**
This is required in order to compile on Ubuntu 24.04.

Otherwise results in the following error:

astra-toolbox/build/linux/python/cython/./astra/CFloat32CustomPython.h:7:40: error: cannot convert ‘PyObject*’ {aka ‘_object*’} to ‘const PyArrayObject*’ {aka ‘const tagPyArrayObject_fields*’}

### CODE REVIEW

**Comment by wjp** [comment]
Does this approach also work for you: https://github.com/wjp/astra-toolbox/commit/864dad753f00567fdd15c16855155d3549d3bf7d ? That way we benefit from cython's type checking.

**Comment by wjp** [comment]
That fix is in master now. Feel free to open a new issue or PR if that didn't resolve your problem too.

**Comment by jmp1985** [comment]
Hi @wjp 

Sorry for the late reply, thanks for this. I have tested and it works for me.

Best wishes

James
